M48
; DRILL file {KiCad 8.0.5} date 2024-10-16T14:13:10+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-16T14:13:10+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0610
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0866
%
G90
G05
T1
X3.234Y-2.776
X3.679Y-2.875
X3.688Y-2.997
T2
X3.4118Y-3.6042
X3.5102Y-3.6042
T3
X3.183Y-3.746
X3.74Y-3.746
T4
X3.0Y-2.68
X3.0Y-3.9
X3.91Y-3.9
X3.92Y-2.67
M30
